### ISSUE TITLE
gamepedia.com

### ISSUE THREAD

**Issue by Markus-Rost** [abp-filters/abp-filters-anti-cv#130]
### List the website(s) where you encounter issues with ABP filters 

* https://minecraft.gamepedia.com/ (all gamepedia subdomains)

### Define the problem 

* Editor tool bar doesn't load when [editing a page](https://minecraft.gamepedia.com/index.php?title=Minecraft_Wiki:Sandbox&action=edit)
* [Custom user javascript](https://minecraft.gamepedia.com/User:MarkusRost/common.js) doesn't load as well
  * Can be noticed on the screenshot, when looking at the sidebar (the `Missbrauchsfilter-Logbuch` link)
  * Reference: https://www.mediawiki.org/wiki/Manual:Interface/JavaScript#Personal_scripts

### Screenshot(s) 

![image](https://user-images.githubusercontent.com/37275477/55276711-0e30f500-52f7-11e9-8e78-357f591671e7.png)
Should look like this:
![image](https://user-images.githubusercontent.com/37275477/55276714-230d8880-52f7-11e9-8c93-27ed2c7d954e.png)

### List all of your filter lists 

Adblock Warning Removal List
ABP filters
EasyList Germany+EasyList

### Tell us about your system configuration 

- Browser and version: Chromium 73
- Adblock Plus version: 3.5

### Other details 

Related to #62, happens since 9e4ab60

**Comment by Mischanix** [comment]
[https://github.com/abp-filters/abp-filters-anti-cv/commit/9e4ab60e5990f9faf6d9d6c9faef35036b592917](This commit) is overly broad by specifying `insert`.  MediaWiki's ResourceLoader on an edit page for many sites in gamepedia has a module called `ext.charinsert` that it tries to load by creating a `<script>` element.  Since ResourceLoader loads these modules via an inline script, the abort-current-inline-script is triggered fairly early in a page's script execution, preventing most MediaWiki JavaScript from running on that page.

If you're looking to circumvent Instart, I'd encourag looking at [how uBlock Origin Extra does it](https://github.com/gorhill/uBO-Extra/blob/master/contentscript.js#L113), since in my experience that method has had far fewer undesirable interactions, probably thanks to that regex being relatively narrow.  In Gamepedia's case, uBO-Extra triggers on the setter for `window.INSTART_TARGET_NAME`, terminating Instart very early in its script execution.
