### ISSUE TITLE
freedownloadskey.com

### ISSUE THREAD

**Issue by smed79** [abp-filters/abp-filters-anti-cv#1425]
**problem**

- popup (revolving adservers)

**site**

- `https://freedownloadskey.com/`

**Comment by Aslatiel** [comment]
Hey @smed79, 

I've been trying to replicate the popups, but so far I cannot get any, I was only able to replicate this redirect that leads nowhere, because Easylist seems to be blocking the rest.

Do you have a way of replicating it?, can you share some more details.

thanks again for the report :smile:
