### ISSUE TITLE
WP Group

### ISSUE THREAD

**Issue by gargul04** [abp-filters/abp-filters-anti-cv#472]
ADS are back: https://github.com/abp-filters/abp-filters-anti-cv/issues/183 + https://github.com/abp-filters/abp-filters-anti-cv/issues/380 + https://github.com/abp-filters/abp-filters-anti-cv/issues/381

**Comment by wizmak** [comment]
Redundant issue from a spamming user, similar to issue #469 deleted by the same user.

**Comment by gargul05** [comment]
You are a perfect example of not only a nasty toxic individual, but also just a fool.
You should have asked me first to explain, rather than aggressively:
- accuse me of spamming
- then silently ban me

<details not-open>
<summary>screenshoot</summary>


![capture_012_14-10-2020_17-14-27](https://user-images.githubusercontent.com/72875495/96011845-c2479180-0e43-11eb-871a-ee55a452b30d.gif)
</details>


Look fool, I haven't removed my issue, it seems github somehow removed it for no reason, thus I just recreated it.
Now, you should remove your github account, because you are unfit for community life, or at least say something like:
"I apologize, I should have asked first." if you want to saty at github, but I have bad feelings that unlike me, you lack any kind of honor, so most probably you will just remove my comment to hide the truth. If you do so, you only confirm what a loser in life you are. Have fun.

**Comment by gargul05** [comment]
You are a perfect example of not only a nasty toxic individual, but also just a fool.
You should have asked me first to explain, rather than aggressively:
- accuse me of spamming
- then silently ban me

<details not-open>
<summary>screenshoot</summary>


![capture_012_14-10-2020_17-14-27](https://user-images.githubusercontent.com/72875495/96011845-c2479180-0e43-11eb-871a-ee55a452b30d.gif)
</details>


Look fool, I haven't removed my issue, it seems github somehow removed it for no reason, thus I just recreated it.
Now, you should remove your github account, because you are unfit for community life, or at least say something like:
"I apologize, I should have asked first." if you want to stay at github, but I have bad feelings that unlike me, you lack any kind of honor, so most probably you will just remove my comment to hide the truth. If you do so, you only confirm what a loser in life you are. Have fun.
