### ISSUE TITLE
https://grammarist.com/

### ISSUE THREAD

**Issue by TheStinkySkunk** [abp-filters/abp-filters-anti-cv#593]
### List the website(s) where you encounter issues with ABP filters 
https://grammarist.com/
* 

### Define the problem 
Blank page with adblock

### Tell us about your system configuration 

- Operating system and version: 
- Browser and version: 
- Adblock Plus version: 

### Other details 

This commit don't allow mistake in html :
https://github.com/abp-filters/abp-filters-anti-cv/commit/38488b95d82c161fcfd1c71f183741db537c5499

**Comment by TheStinkySkunk** [comment]
Don't close this before all functionnalities are restored ...

As usual, you publish anything without bothering to check

This rules don't RESPECT W3C HTML5.

**Comment by arsykan** [comment]
@TheStinkySkunk

> You must check ALL website concerned before publish a bullshit rule like that.

> Some website have functionality disabled by your rules.

> Why don't work like pro ?

this language is not acceptable, change it in the future or otherwise you will be ignored.

you filed 1 issue for 1 website & it was resolved. the filter works perfectly for those websites, don't play deliberate changes after & break the website.

if you have other issues with other websites file them.
