### ISSUE TITLE
Just recognize it as official....

### ISSUE THREAD

**Issue by zpfzezefuhzeifu** [abp-filters/abp-filters-anti-cv#929]
FFS

reddit.com/r/adblockp

**Comment by zpfzezefuhzeifu** [comment]
...

**Comment by manuel-martinez-dev** [comment]
Hello again,

as mentioned previously [here](https://github.com/abp-filters/abp-filters-anti-cv/issues/927) and commented [here](https://github.com/abp-filters/abp-filters-anti-cv/issues/928)... there's is no need for this reddit page.

There really is no need to create an issue for this again, since it was already answered twice, if created again it will most likely just be closed without any further acknowledgement from us.

thanks again for the suggestion.
