### ISSUE TITLE
https://jpscan-vf.com/

### ISSUE THREAD

**Issue by felippesantos46** [abp-filters/abp-filters-anti-cv#976]
### List the website(s) where you encounter issues with ABP filters 

* https://jpscan-vf.com/

### Define the problem 
Recurrent changes in adservers (numbers/letters), regex could be created but maybe this rule would be a good shot:
`jpscan-vf.com#$#abort-on-property-read __formatsGetters`

Maybe it would work for other AdManager examples

### Screenshot(s) 
<img width="1077" alt="Screenshot 2022-05-19 at 10 02 52" src="https://user-images.githubusercontent.com/65717387/169244025-e8306f78-73bb-4be0-a74f-260743a05649.png">
<img width="1440" alt="Screenshot 2022-05-19 at 09 58 22" src="https://user-images.githubusercontent.com/65717387/169244034-af9b53cc-af65-49ae-8c9d-653c4c442aaa.png">

**Comment by dimisa-RUAdList** [comment]
@manuel-martinez-dev 
This problem is quite common.

In RU AdList, this is solved as follows: `/^https?://[0-9a-f]{10}\.[0-9a-f]{10}\.com\/[0-9a-f]{32}\.js$/$third-party,script`

AdGuard Base has almost the same rule: `/^https:\/\/[0-9a-f]{10}\.[0-9a-f]{10}\.com\/[0-9a-f]{32}\.js$/$script,third-party`

**Comment by felippesantos46** [comment]
Agreed, on the other hand i believe this regex won't be added in EL EL. 
I have a similar rule in EL ES, for other well known problem. 

That's why i've requested the rule in here 😄
